#!/usr/bin/env python3
"""Sanity-check the arm-marker calibration end-to-end.

Reads:
  - arm_marker_calibration.json (marker IDs, cart-to-arm rotation, T_E_P)
  - Live: 4 marker world positions  → arm base translation t_W_A
  - Live: cart rigid body orientation → arm base rotation R_W_A
  - Live: OpenSai cartesian_task::current_position / current_orientation → T_A_E
Computes and prints:
  - T_W_A   (arm base in world)
  - T_W_E   (end-effector / flange in world, = T_W_A ⊕ T_A_E)
  - T_W_P   (racket sweet-spot in world, = T_W_E ⊕ T_E_P)

You then visually / tape-measure verify:
  - t_W_A matches the physical location of the Franka base on the cart.
  - t_W_E matches the physical flange location.
  - t_W_P matches the physical paddle sweet-spot location.

Pure read — does not move anything. Safe to run anytime.

`--init` creates a starter JSON at the canonical path with sensible defaults
(matching the racket geometry from sports_bot/state_machine/config.py) if no
calibration exists, so you have something to edit.

Prereqs:
  1. Redis running.
  2. StreamDataSkeleton.py running (labeled marker streaming enabled in Motive).
  3. OpenSai cartesian controller running (for the EE pose read; can skip with
     --no-ee to just verify T_W_A).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import numpy as np
import redis

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_SPORTS_BOT_DIR = os.path.dirname(_THIS_DIR)
_OPENSAI_DIR = os.path.dirname(_SPORTS_BOT_DIR)
if _OPENSAI_DIR not in sys.path:
    sys.path.insert(0, _OPENSAI_DIR)

from sports_bot.utils.frames import (  # noqa: E402
    arm_marker_calibration_path,
    axis_angle_from_R,
    compute_T_W_A_from_markers,
    load_arm_marker_calibration,
    marker_world_position_key,
    read_marker_position_W,
    save_arm_marker_calibration,
    se3_compose,
)


# OpenSai EE pose keys (cartesian_task::current_*). Matches test_swing.py /
# pickleball_fsm.py's adapter — robot name is "FrankaRobot" on real hardware.
EE_POS_FMT = ("opensai::controllers::{robot}::cartesian_controller::"
              "cartesian_task::current_position")
EE_ORI_FMT = ("opensai::controllers::{robot}::cartesian_controller::"
              "cartesian_task::current_orientation")


# ---------- Starter JSON ------------------------------------------------------

def _write_starter(path: str, args: argparse.Namespace) -> None:
    """Build a starter arm_marker_calibration.json with default racket
    geometry pulled from sports_bot/state_machine/config.py.

    Defaults:
        marker_specs        = [[11,1],[11,2],[11,3],[11,4]]
        cart_rigid_body_id  = 11
        R_cart_to_arm       = identity
        T_E_P translation   = [0, 0, 0.368]   (config.py sweet_spot_in_flange)
        T_E_P rotation      = aligns racket +Z with EE +X (face_normal_in_flange)
                              and racket +Y with EE +Z. Columns:
                                racket +X in EE = [0, 1, 0]   (EE +Y)
                                racket +Y in EE = [0, 0, 1]   (EE +Z)
                                racket +Z in EE = [1, 0, 0]   (EE +X = face normal)
    """
    from sports_bot.utils.frames import _se3_to_dict  # noqa: PLC0415 - local helper

    # Default racket rotation (see docstring above):
    T_E_P_rot = np.array([
        [0.0, 0.0, 1.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
    ])
    T_E_P_trans = np.array([0.0, 0.0, 0.368])

    marker_specs = [(11, i + 1) for i in range(args.n_markers)]
    save_arm_marker_calibration(
        path,
        marker_specs=marker_specs,
        cart_rigid_body_id=args.cart_rigid_body_id,
        R_cart_to_arm=np.eye(3),
        T_E_P=(T_E_P_rot, T_E_P_trans),
        metadata={
            "comment_starter": (
                "STARTER FILE — generated by verify_arm_calibration.py --init. "
                "EDIT THIS before relying on it: pick the actual 4 marker IDs "
                "from `list_markers.py`, verify T_E_P matches your paddle mount "
                "(translation in flange Z, rotation aligning sweet-spot frame). "
                "Then re-run verify_arm_calibration.py (without --init) to "
                "sanity-check."
            ),
            "initialized_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        },
    )


# ---------- Helpers -----------------------------------------------------------

def _read_T_A_E(r: redis.Redis, robot: str):
    pos_raw = r.get(EE_POS_FMT.format(robot=robot))
    ori_raw = r.get(EE_ORI_FMT.format(robot=robot))
    if pos_raw is None or ori_raw is None:
        return None
    try:
        pos = np.asarray(json.loads(pos_raw), dtype=float)
        ori = np.asarray(json.loads(ori_raw), dtype=float)
    except (json.JSONDecodeError, TypeError, ValueError):
        return None
    if pos.shape != (3,) or ori.shape != (3, 3):
        return None
    return (ori, pos)


def _format_se3(label: str, T) -> str:
    R, t = T
    omega = axis_angle_from_R(R)
    angle_deg = math.degrees(float(np.linalg.norm(omega)))
    axis = omega / max(1e-9, float(np.linalg.norm(omega)))
    return (f"  {label}:\n"
            f"    t = [{t[0]:+.4f}, {t[1]:+.4f}, {t[2]:+.4f}] m\n"
            f"    R = axis [{axis[0]:+.3f}, {axis[1]:+.3f}, {axis[2]:+.3f}], "
            f"angle {angle_deg:+.2f}°")


# ---------- Main flow ---------------------------------------------------------

def run(args: argparse.Namespace) -> int:
    out_path = args.calibration or arm_marker_calibration_path()

    # --init: just write the starter and bail.
    if args.init:
        if os.path.isfile(out_path) and not args.force:
            print(f"[verify] {out_path} already exists. Pass --force to overwrite.")
            return 1
        _write_starter(out_path, args)
        print(f"[verify] wrote starter calibration to {out_path}")
        print(f"[verify] EDIT the marker_specs (4 IDs from `list_markers.py`) "
              f"and confirm T_E_P matches your paddle, then re-run.")
        return 0

    if not os.path.isfile(out_path):
        print(f"[verify] no calibration at {out_path}.")
        print(f"         run with --init to write a starter, then edit it.")
        return 1
    cal = load_arm_marker_calibration(out_path)
    print(f"[verify] loaded {out_path}")
    print(f"         marker_specs        = {cal.marker_specs}")
    print(f"         cart_rigid_body_id  = {cal.cart_rigid_body_id}")
    print(f"         R_cart_to_arm       = identity? "
          f"{'yes' if np.allclose(cal.R_cart_to_arm, np.eye(3)) else 'NO'}")
    print()

    r = redis.Redis(host=args.redis_host, port=args.redis_port,
                    decode_responses=True)
    try:
        r.ping()
    except redis.exceptions.ConnectionError as e:
        print(f"[verify] Cannot reach Redis: {e}")
        return 1

    # Per-marker visibility
    print(f"  per-marker visibility:")
    for spec in cal.marker_specs:
        key = marker_world_position_key(spec[0], spec[1])
        p = read_marker_position_W(r, spec)
        if p is None:
            print(f"    {key} — MISSING (not visible / streamer not running / "
                  f"labeled markers disabled in Motive)")
        else:
            print(f"    {key} — [{p[0]:+.4f}, {p[1]:+.4f}, {p[2]:+.4f}] m")
    print()

    T_W_A = compute_T_W_A_from_markers(
        r, cal.marker_specs, cal.cart_rigid_body_id,
        R_cart_to_arm=cal.R_cart_to_arm,
    )
    if T_W_A is None:
        print(f"[verify] cannot compute T_W_A — some markers or the cart "
              f"rigid body aren't currently visible.")
        return 1

    print(_format_se3("T_W_A (arm base in world)", T_W_A))

    if args.no_ee:
        print(f"\n[verify] --no-ee set — skipping T_W_E / T_W_P computation.")
        return 0

    T_A_E = _read_T_A_E(r, args.robot_name)
    if T_A_E is None:
        print(f"\n[verify] cannot read EE pose from "
              f"{EE_POS_FMT.format(robot=args.robot_name)}.")
        print(f"         is OpenSai cartesian_controller running on robot "
              f"'{args.robot_name}'?  pass --no-ee to verify just T_W_A.")
        return 1

    T_W_E = se3_compose(T_W_A, T_A_E)
    T_W_P = se3_compose(T_W_E, cal.T_E_P)

    print(_format_se3("T_A_E (EE in arm base, from OpenSai)", T_A_E))
    print(_format_se3("T_W_E (EE flange in world)", T_W_E))
    print(_format_se3("T_E_P (sweet spot in EE, persisted)", cal.T_E_P))
    print(_format_se3("T_W_P (racket sweet spot in world)", T_W_P))

    print()
    print(f"[verify] sanity check by eye:")
    print(f"  - t_W_A should match the physical Franka base location on the cart")
    print(f"  - t_W_E should match the physical flange location")
    print(f"  - t_W_P should match the physical paddle sweet-spot location")
    print(f"  - racket +Z (column 2 of T_W_P[0]) should point in the paddle's "
          f"face-normal direction")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--calibration", default=None,
                        help="Path to arm_marker_calibration.json. Default: "
                             "sports_bot/optitrack/arm_marker_calibration.json")
    parser.add_argument("--robot-name", default="FrankaRobot",
                        help="OpenSai robot name for the EE pose Redis keys.")
    parser.add_argument("--no-ee", action="store_true",
                        help="Skip the EE / sweet-spot computation (useful "
                             "when OpenSai isn't running).")
    parser.add_argument("--init", action="store_true",
                        help="Write a starter calibration JSON if none exists "
                             "and exit. Then edit it and re-run.")
    parser.add_argument("--n-markers", type=int, default=4,
                        help="(--init only) Number of marker_spec entries in "
                             "the starter file. Defaults to 4.")
    parser.add_argument("--cart-rigid-body-id", type=int, default=11,
                        help="(--init only) Cart Streaming ID in Motive.")
    parser.add_argument("--force", action="store_true",
                        help="(--init only) Overwrite existing calibration.")
    parser.add_argument("--redis-host", default="localhost")
    parser.add_argument("--redis-port", type=int, default=6379)
    args = parser.parse_args()

    try:
        rc = run(args)
    except KeyboardInterrupt:
        print("\n[verify] interrupted.")
        rc = 130
    sys.exit(rc)


if __name__ == "__main__":
    main()
